apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processing-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-processing
  template:
    metadata:
      labels:
        app: order-processing
    spec:
      containers:
      - name: order-processing
        image: yashmahi04/order-processing1:latest
        ports:
        - containerPort: 5000
        env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: order-processing-secret
              key: db_password
