---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present

- name: Copy Nginx configuration
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf

- name: Deploy index.html to Nginx
  ansible.builtin.copy:
    src: index.html
    dest: /usr/share/nginx/html/index.html

- name: Ensure Nginx is running
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: yes
